# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    #agrega hostname para poder ingresar server desde adminer
    hostname: sprint
    container_name: sprint
    restart: always
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: example
      # POSTGRES_DB: m7-abp_1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: biblioteca
    ports:
      - 5432:5432

  adminer:
    image: adminer
    hostname: adminer
    container_name: sprintm7
    restart: always
    ports:
      - 8080:8080